---

- name: Set up environment
  hosts: all
  become: true
  tags: environment
  vars_files:
    - vars/main.yml
  pre_tasks:
  - name: Update and upgrade apt packages
    become: true
    apt:
      upgrade: yes
      update_cache: yes
  roles:
    - singleplatform-eng.users
    - geerlingguy.swap
    - geerlingguy.security
    - geerlingguy.firewall
    - geerlingguy.docker

- name: Set up masternode
  hosts: all
  become: true
  become_user: '{{ dash_user }}'
  tags: masternode
  vars_files:
    - vars/main.yml
  tasks:
  - name: Pull docker setup repository
    git:
      repo: 'https://github.com/strophy/dash-masternode-docker.git'
      dest: /home/dash/dash-masternode-docker
  - name: Run masternode setup
    shell:
      chdir: /home/dash/dash-masternode-docker/
      cmd: dash.sh
